### ISSUE TITLE
Showing User Specific Information on the Profile Page

### ISSUE THREAD

**Issue by esnowgol** [COSC481W-2024Fall/Ript-Fitness#11]
**User Story**
As someone trying to User trying to Improve their personal fitness while connecting with others, I would like to be able to see my improvements in a quantifiable way, see my friends, and edit my account so that I can properly see my journey, and stay motivated.

- **Persona**: Someone who is trying to improve their personal fitness and connect with their friends
- **Feature**: Show quantifiable data to showcase the user's workout journey, and allow them to edit their account or view friends
- **Bussiness Value**: Staying motivated by seeing quantifiable improvements, as well as being motivated by the connections they have in the app.

**Tasks**
- [x] Create a Profile page that displays the User's friends
- [x] On the Profile page, create a calendar to showcase the user's dedication to working out.
- [x] On the Profile page, create a button to navigate to the graphs screen to help them visualize their progress.
- [x] On the Profile page, create a button to navigate to the Foods screen to help them track foods.

**Acceptance Tests**
The User can Navigate to the profile page
The User is able to see a Mock friends list.
The User can see a Mock calendar of days they've worked out
The user can see a Mock Graph for displaying data

**Acceptance Criteria**
User can navigate to the profile page
User can see their friends from their profile page
User can View an accurately filled calendar for the days they've worked out
User can view a graph that accurately showcases their progress on workouts.
