### ISSUE TITLE
Add Workout Screen Update

### ISSUE THREAD

**Issue by hoangnatalie** [COSC481W-2024Fall/Ript-Fitness#179]
# Product Backlog Item (User Story)

As a **User**, the **Add Workouts screen** is too confusing, so I'd like it to be more user friendly.

**Persona:** Misho wants the Add Workouts screen to be updated, so it's less confusing to use.
**Feature:** UI improvement to the Add Workouts screen.
**Business Value:** This feature will help users use the Add Workouts screen correctly.

## Description
Add Workout screen is very confusing for test users, offering no helpful indicators on how to navigate the screen.

## Task List

- [x] Add a message when the workout screen is empty (has no exercises).
- [x] Submit button will be disabled until the user adds at least one exercise.
- [x] More text to tell users to add a workout name.
- [x] Change the submit button to "create workout"
- [x] After pressing the create workout button, the user will be taken to the My Workouts page. 

## Acceptance Criteria
1. Button is disabled until at least one exercise is added.
2. After creating workout, the user is brought to My Workouts

## Acceptance Tests
**Test 1**
- **Steps**: Press create button with out an exercise
- **Expected Outcome**:  button is disabled and shouldn't allow user to click on it.
**Test 2**
- **Steps**: Press create button
- **Expected Outcome**:  workout is added to My Workouts and the user is brought to that screen.

## From beta users:
"When I saw the search bar, I thought I could look up exercises to add." - Misho
7 out of 10 beta testers were confused by this screen.
