### ISSUE TITLE
Connect backend to frontend graph, fix crashing bugs, and allow delete post feature

### ISSUE THREAD

**Issue by robhewison** [COSC481W-2024Fall/Ript-Fitness#181]
# Product Backlog Item (User Story)

As a **User**, I want to see graph data, delete my posts, and stop the app from crashing

**Persona:** 
The user is a ripped dude who wants his workout app to function seemlessly. Also he wants to delete his posts in case he posts something by accident or something he regrets. 

**Feature:** 
- Delete posts on frontend
- Have graph populated with data
- Fix misc bugs like crashing (white screen crash out)

**Business Value:** 
Having the user be able to delete their posts would make them happier which would overall be good for the business. Also fixing the crashing bugs is paramount to a good application

## Description
There are three things that will be done:
- Fix the crashing issues when posting comments and graph
- Add data to the graph that is on the frontend
- Allow users to delete their own posts after they've posted them

## Task List

- [x] add delete button on user's own posts
- [x] fix bugs with posting comments and graph (white crash out) 
- [x] populate the graph with data from the backend
