### ISSUE TITLE
Front Page (Login and create an account)

### ISSUE THREAD

**Issue by nhalash** [COSC481W-2024Fall/Ript-Fitness#4]
# Product Backlog Item (User Story)

As a **User**, I want to **Create an account** so that **I can log into the app; and, save my information into my profile and see my info at a later date**.

Persona: A person who wants to create an account.
Feature: The front page (log in and create an account) will allow a user to create an account.
Business value: This will allow our users to create an account which gives them access to all the apps features.

## Description

**Feature Name**: [Log in & Create an account page]
**Description**: [The login/create an account page will allow a user to either create an account or login if they already have an account. The login feature will allow users to access their saved data. ]

## Task List

1. [x] Create a controller, service, repository, and data model for user accounts.
2. [x] Create the add new account feature
3. [x] Create the login feature
4. [x] Test these features
5. [x] Add encryption for passwords/emails

## Acceptance Criteria

- [New accounts should only be created if it doesn't already exist (username)]
- [To log in the username and password must be in the database (Account must be already created)]
- [If a username does not exist, login should fail and user should be redirected to create a new account]

## Acceptance Tests

**Test 1**
- **Steps**: [test creating account]
- **Expected Outcome**: [Account should be created, passing all logic that is described above]

**Test 2**
- **Steps**: [test login]
- **Expected Outcome**: [Login should be succesfull, passing all logic that is described above]
