### ISSUE TITLE
Notes Functionality/ Screen

### ISSUE THREAD

**Issue by hoangnatalie** [COSC481W-2024Fall/Ript-Fitness#42]
# Product Backlog Item (User Story)

As a **User**, I want to **a notes function/ notes screen** so that **I can add specific notes for that workout such as rest times, seat position, or general information**.

**Persona:** Misho wants to add notes to his workouts.
**Feature:** Notes functionality - a user can access a notes page from the workout tab and create multiple notes for an exercise.
**Business Value:** Having a notes function separates this app from other gym apps that do note have this feature.

## Description

**Feature Name**: Notes feature and Screen
**Description**: The add workouts page has an icon (arrow) for users to be able to add notes. Add the functionality to allow users to add notes. A new screen is needed to look back at previous notes.

## Task List

- [x] Add "My Notes" button to Workouts tab
- [x] Create "My Notes" screen (first one)
- [x] Create second screen for specific note page.
- [ ] Note icon (comment bubble w/ lines or ellipses) will appear on an exercise if there's a note for that workout. [Did Not Complete]

## Acceptance Criteria
- Users should be able to go to the notes page
- Users should be able to add a note to a workout

## Acceptance Tests

**Test 1**
- **Steps**: [Steps for Test 1]
- **Expected Outcome**:  the "My Notes" button goes to the correct screen.

Extra note from team: 
Can you possibly include a notes section for each workout? I like to write down relevant details for each workout like seat position, rest times between sets, or just general notes about each workout. We could store it as a String in the db and can be nullable if there’s no notes

Update:
Currently, I used Context to be able to create and edit notes. This will be changed.
