### ISSUE TITLE
Create the backend functionality for exercises (Exercise class)

### ISSUE THREAD

**Issue by nhalash** [COSC481W-2024Fall/Ript-Fitness#46]
# Product Backlog Item (User Story)

As a **User**, I want to **Add an Exercise** so that **I can save all my exercises in the workout tab**.

Persona: A person who wants to save their exercises.
Feature: The add exercise page will allow the user to add an exercise so that they can add it to a workout and use it later.
Business value: This will allow reusability for users so that they can save time by having pre-saved exercises.

## Description

**Feature Name**: [Add exercises]
**Description**: [The user will be able to add an exercise; which will later be able to be added to a workout. The user can make up an exercise from scratch or select a pre-built exercise (which can also be edited)]

## Task List

1. [x] Create a controller, service, repository, and data model for 'Exercise'.
2. [x] Make sure that my class links correctly with the Workout class that Chris.M is working on
3. [x] Write tests for these features
4. [x] Make sure that the front end can access and correctly use my endpoints
5. [x] Implement User sessions (using JWT tokens)

## Acceptance Criteria
- [Every exercise should have its own unique ID (even if the exercise is the exact same as one that already exists)]
- [Every exercise should be traceable to a user account]
- [An exercise should be editable]

## Dependencies
- [Accounts classes (service and repository layer)]
- [Streak class]

## Acceptance Tests

**Test 1**
- **Steps**: [test creating exercise]
- **Expected Outcome**: [Exercise should be created; with its own ID, and a reference to the user that created it (user_ID) and a reference to the workout that it belongs to (workout_ID)]

**Test 2**
- **Steps**: [test editing a exercise]
- **Expected Outcome**: [When an exercise gets edited; only the (sets, reps, weight, and name) should be editable]
