### ISSUE TITLE
Welcome Pages

### ISSUE THREAD

**Issue by hoangnatalie** [COSC481W-2024Fall/Ript-Fitness#9]
# Product Backlog Item (User Story)

As a **User**, I want to **create an account and log in** so that **save my progress and access the app**.

**Persona:** Misho wants enter a gym app with a friendly UI.
**Feature:** UI pages for welcoming the user (Misho), a page to let them sign up, and a page to log in.
**Business Value:** Having a friendly UI makes Misho want to continue to use the app.

## Description

**Feature Name**: Welcome pages - log in and sign up
**Description**: When the user opens the app, they will see a welcome page. Then, they can either sign up or login in with their respective page.

## Task List

- [x] Create button components to reuse for each page
- [x] Add logo to each page
- [x] Text for welcoming and directions
- [x] Input boxes for sign up and log in

## Acceptance Criteria

- Users should be able to traverse these 3 pages
- Log in and sign up need input boxes 
- Each page has the logo 

## Acceptance Tests

**Test 1**
- **Steps**: [Steps for Test 1]
- **Expected Outcome**: Buttons have animation (pressed)

**Test 2**
- **Steps**: [Steps for Test 2]
- **Expected Outcome**: Each page has the logo displayed

**Test 3**
- **Steps**: [Steps for Test 3]
- **Expected Outcome**: Each page has text with directions for their specific screen.

**Test 4**
- **Steps**: [Steps for Test 4]
- **Expected Outcome**: Login and signup need input boxes.
- The password input box needs an eye icon and when a user types, the password must be hidden.
